const SET_RESTAURANTS = "SET_RESTAURANTS";
const SET_TYPE = "SET_TYPE";
const FILTER_RESTAURANTS = "FILTER_RESTAURANTS";
const SET_LOADING = "SET_LOADING";
const SET_RESTAURANT_FAILURE = "SET_RESTAURANT_FAILURE";

export {
  SET_RESTAURANTS,
  SET_TYPE,
  FILTER_RESTAURANTS,
  SET_LOADING,
  SET_RESTAURANT_FAILURE,
};
